#!/usr/bin/env python3

# abyscrypt version 0.618
# https://github.com/hairetikos/abysscrypt

import sys
from PyQt5.QtWidgets import QApplication
from wizard import AbyssCryptWizard

if __name__ == "__main__":
    app = QApplication(sys.argv)
    app.setApplicationName("abysscrypt")
    app.setStyle("Fusion")
    
    wizard = AbyssCryptWizard()
    wizard.show()
    
    sys.exit(app.exec_())
