#!/usr/bin/env python3

class ScriptGenerator:
    def __init__(self, levels):
        self.levels = levels
        self.mapper_prefix = "abysscrypt"
    
    def generate_mount_script(self):
        """Generate a script to mount the multi-level encryption"""
        script = []
        script.append("#!/bin/bash")
        script.append("\n# abysscrypt mount script - Generated by abysscrypt\n")
        
        # Add error handling
        script.append("set -uo pipefail")
        script.append("function cleanup {")
        script.append("    echo 'Error occurred. Cleaning up...'")
        script.append("    for ((i=${#MOUNTED_LEVELS[@]}-1; i>=0; i--)); do")
        script.append("        cryptsetup close \"${MOUNTED_LEVELS[$i]}\" 2>/dev/null || true")
        script.append("    done")
        script.append("}\n")
        script.append("MOUNTED_LEVELS=()")
        
        # Root privilege check
        script.append("\n# Check for root privileges")
        script.append('if [ "$(id -u)" -ne 0 ]; then')
        script.append('    echo "Error: This script must be run as root (or with sudo)."')
        script.append('    exit 1')
        script.append('fi')
        
        # Mount point validation (moved before container prompt)
        script.append("\n# Define mount point")
        script.append("MOUNT_POINT=\"$1\"")
        script.append("if [ -z \"$MOUNT_POINT\" ]; then")
        script.append("    echo 'Usage: please specify <mount_point>'")
        script.append("    exit 1")
        script.append("fi")
        script.append("mkdir -p \"$MOUNT_POINT\"")
        
        # Container prompt
        script.append("\n# Get container information")
        script.append('echo "Enter path to container file or device:"')
        script.append('read -r CONTAINER_PATH')
        
        # Check if path exists and create file if needed
        script.append('if [ ! -e "$CONTAINER_PATH" ]; then')
        script.append('    # Path does not exist')
        script.append('    echo "Path $CONTAINER_PATH does not exist."')
        script.append('    if [[ "$CONTAINER_PATH" != "/dev/"* ]]; then')
        script.append('        # Not a device path, assume it\'s a file')
        script.append('        echo "Would you like to create a container file at this path? (y/n)"')
        script.append('        read -r CREATE_FILE')
        script.append('        if [[ "$CREATE_FILE" =~ ^[Yy] ]]; then')
        script.append('            DIR_PATH=$(dirname "$CONTAINER_PATH")')
        script.append('            if [ ! -d "$DIR_PATH" ]; then')
        script.append('                echo "Creating directory $DIR_PATH..."')
        script.append('                mkdir -p "$DIR_PATH"')
        script.append('            fi')
        script.append('            echo "Enter size in MB:"')
        script.append('            read -r SIZE_MB')
        script.append('            if ! [[ "$SIZE_MB" =~ ^[1-9][0-9]*$ ]]; then')
        script.append('                echo "Invalid size. Must be a positive integer."')
        script.append('                exit 1')
        script.append('            fi')
        script.append('            echo "Creating file of ${SIZE_MB}MB. This may take a while..."')
        script.append('            # Using urandom to fill the container for plausible deniability')
        script.append('            # (random data makes it harder to distinguish encrypted from unused space)')
        script.append('            dd if=/dev/urandom of="$CONTAINER_PATH" bs=1M count="$SIZE_MB" status=progress')
        script.append('            echo "File created successfully."')
        script.append('        else')
        script.append('            echo "Operation cancelled."')
        script.append('            exit 1')
        script.append('        fi')
        script.append('    else')
        script.append('        echo "Device path does not exist. Please check the device name and try again."')
        script.append('        exit 1')
        script.append('    fi')
        script.append('elif [ -d "$CONTAINER_PATH" ]; then')
        script.append('    echo "Error: $CONTAINER_PATH is a directory. Please specify a file or device path."')
        script.append('    exit 1')
        script.append('fi\n')
        
        # Set up each level
        script.append(f"\n# Setting up {len(self.levels)} levels of encryption")
        
        for i, level in enumerate(self.levels):
            level_num = level.level_num
            mapper_name = f"{self.mapper_prefix}_{level_num}"
            script.append(f"\n# Level {level_num} encryption setup")
            
            # For level 1, source is the container provided at runtime
            if i == 0:
                source = "$CONTAINER_PATH"
            else:
                source = f"/dev/mapper/{self.mapper_prefix}_{level_num-1}"
            
            # Prepare offset flag if needed
            offset_flag = f" --offset {level.offset}" if level.offset > 0 else ""
            if level.offset > 0:
                script.append(f"# Using offset {level.offset} sectors for level {level_num}")
            
            # Auth method
            if level.use_passphrase:
                script.append(f"echo 'Level {level_num}:'")
                script.append(f"cryptsetup open {source} {mapper_name} --type plain --cipher {level.cipher} --key-size {level.key_size} --hash {level.hash_type}{offset_flag} || {{ cleanup; exit 1; }}")
            else:
                # For keyfile mode, use --hash plain to avoid version-dependent hashing
                auth_method = f"--key-file=\"{level.keyfile_path}\""
                script.append(f"cryptsetup open {source} {mapper_name} --type plain --cipher {level.cipher} --key-size {level.key_size} --hash plain {auth_method}{offset_flag} || {{ cleanup; exit 1; }}")

            script.append(f"MOUNTED_LEVELS+=('{mapper_name}')")
        
        # Final mapper device
        final_mapper = f"/dev/mapper/{self.mapper_prefix}_{self.levels[-1].level_num}"
        
        # Check if the device needs formatting and offer to create a filesystem
        script.append("\n# Check if filesystem exists on the final device")
        script.append(f"if ! blkid {final_mapper} > /dev/null 2>&1; then")
        script.append("    echo 'No filesystem detected on the encrypted device.'")
        script.append("    echo 'Would you like to create an ext4 filesystem? (y/n)'")
        script.append("    read -r CREATE_FS")
        script.append("    if [[ \"$CREATE_FS\" =~ ^[Yy] ]]; then")
        script.append(f"        echo 'Creating ext4 filesystem on {final_mapper}...'")
        script.append(f"        mkfs.ext4 -O ^has_journal,^metadata_csum,^resize_inode -m 0 {final_mapper}")
        script.append("        echo 'ext4 filesystem created with 0% reserved area. disabled features: journal, metadata_checksum, resize_inode'")
        script.append("        # Mount the final encrypted volume")
        script.append(f"        mount -o noatime {final_mapper} \"$MOUNT_POINT\"")
        script.append("        echo 'Multi-level encryption setup complete!'")
        script.append(f"        echo \"Mounted at $MOUNT_POINT\"")
        script.append("    else")
        script.append("        echo 'No filesystem created. Encrypted device is ready but not mounted.'")
        script.append("        echo 'You can manually create a filesystem later and mount it.'")
        script.append("        echo 'Multi-level encryption setup complete!'")
        script.append("    fi")
        script.append("else")
        script.append("    # Filesystem exists, mount it")
        script.append("    echo 'Existing filesystem detected. Mounting...'")
        script.append(f"    mount -o noatime {final_mapper} \"$MOUNT_POINT\"")
        script.append("    echo 'Multi-level encryption setup complete!'")
        script.append(f"    echo \"Mounted at $MOUNT_POINT\"")
        script.append("fi")

        return "\n".join(script)
    
    def generate_unmount_script(self):
        """Generate a script to unmount the multi-level encryption"""
        script = []
        script.append("#!/bin/bash")
        script.append("\n# abyssCrypt unmount script - Generated by abysscrypt\n")
        
        # Add error handling
        script.append("set -uo pipefail")
        
        # Root privilege check
        script.append("\n# Check for root privileges")
        script.append('if [ "$(id -u)" -ne 0 ]; then')
        script.append('    echo "Error: This script must be run as root (or with sudo)."')
        script.append('    exit 1')
        script.append('fi')
        
        # Mount point
        script.append("\n# Define mount point")
        script.append("MOUNT_POINT=\"$1\"")
        script.append("if [ -z \"$MOUNT_POINT\" ]; then")
        script.append("    echo 'Usage: please specify <mount_point>'")
        script.append("    exit 1")
        script.append("fi\n")
        
        script.append("# Unmount the filesystem")
        script.append("echo 'Unmounting encrypted filesystem...'")
        script.append("if ! umount \"$MOUNT_POINT\"; then")
        script.append("    echo 'Warning: Failed to unmount. Device may be busy.'")
        script.append("    echo 'Proceeding to close encryption layers anyway...'")
        script.append("fi")
        
        # Close each level in reverse order
        for level in reversed(self.levels):
            level_num = level.level_num
            mapper_name = f"{self.mapper_prefix}_{level_num}"
            script.append(f"\n# Closing Level {level_num}")
            script.append(f"cryptsetup close {mapper_name} || echo 'Warning: Failed to close {mapper_name}'")
        
        script.append("\necho 'Multi-level encryption teardown complete!'")
        
        return "\n".join(script)
